version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: protectorai-web
    ports:
      - "5173:80" # external 5173 â†’ container 80
    restart: unless-stopped
    networks:
      - protectorai-network

networks:
  protectorai-network:
    driver: bridge
